// generated from rosidl_generator_cpp/resource/idl.hpp.em
// generated code does not contain a copyright notice

#ifndef LLL_RDM_MSGS__MSG__PLANNING_CONSISTENCY_TRACKING_ERROR_HIGH_FREQUENCY_MSG_HPP_
#define LLL_RDM_MSGS__MSG__PLANNING_CONSISTENCY_TRACKING_ERROR_HIGH_FREQUENCY_MSG_HPP_

#include "lll_rdm_msgs/msg/detail/planning_consistency_tracking_error_high_frequency_msg__struct.hpp"
#include "lll_rdm_msgs/msg/detail/planning_consistency_tracking_error_high_frequency_msg__builder.hpp"
#include "lll_rdm_msgs/msg/detail/planning_consistency_tracking_error_high_frequency_msg__traits.hpp"
#include "lll_rdm_msgs/msg/detail/planning_consistency_tracking_error_high_frequency_msg__type_support.hpp"

#endif  // LLL_RDM_MSGS__MSG__PLANNING_CONSISTENCY_TRACKING_ERROR_HIGH_FREQUENCY_MSG_HPP_
